apiVersion: v1
kind: Secret
metadata:
  name: git-clone-https
  namespace: flux-system
type: Opaque
data:
  # password: base64-Personal-Access-Token
  # username: base64-user-name
  password: Z2hwX0tnQ1VNS1dPQ2s1M3BGZlVvUW1ZSm1EM1BqUnA3TTRiVFB5UA==
  username: dGhtN3g=
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: devops-repo
  namespace: flux-system
spec:
  interval: 5m #git clone间隔
  url: https://code.pypygo.com/vertex/ollie.git
  ref:
    # 直接检查指定commit hash，commit hash git里全局唯一 可复用
    # NEW_COMMIT="newcode----"
    # sed -i "/^    commit: /s/: .*/: \"$NEW_COMMIT\"/"  flux-gitrepo.yaml 
    commit: "newcode----"
  secretRef:
    name: git-clone-https
---
#prod-cluster 环境的gitops
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: devops-kz
  namespace: flux-system
spec:
  path: "./_deploy/prod-cluster/svc-kustomize"

  interval: 10m # apply间隔
  suspend: true #暂停同步,恢复则直接注释掉该行即可
  prune: true #强一致性同步
  targetNamespace: flux-system #关联指定ns里的source
  sourceRef:
    kind: GitRepository
    name: devops-repo

  timeout: 1m