# Options for analysis running.
run:
  # include `vendor` `third_party` `testdata` `examples` `Godeps` `builtin`
  skip-dirs-use-default: true
  skip-dirs:
    - kitex_gen
  skip-files:
    - ".*\\.mock\\.go$"
    - ".*\\_test\\.go$"
# output configuration options
output:
  # Format: colored-line-number|line-number|json|tab|checkstyle|code-climate|junit-xml|github-actions
  format: colored-line-number
# All available settings of specific linters.
# Refer to https://golangci-lint.run/usage/linters
linters-settings:
  gocyclo:
    # Minimal code complexity to report.
    # Default: 30 (but we recommend 10-20)
    min-complexity: 10
  gofumpt:
    # Choose whether to use the extra rules.
    # Default: false
    extra-rules: true
  govet:
    # Disable analyzers by name.
    # Run `go tool vet help` to see all analyzers.
    disable:
      - stdmethods
linters:
  enable:
    - gofumpt
    - gofmt
  disable:
    - errcheck
    - typecheck
    - deadcode
    - varcheck
    - staticcheck
issues:
  exclude-use-default: true
