// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	TAccount      *tAccount
	TAllAuthxRule *tAllAuthxRule
	TApipath      *tApipath
	TBuildService *tBuildService
	TRelease      *tRelease
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	TAccount = &Q.TAccount
	TAllAuthxRule = &Q.TAllAuthxRule
	TApipath = &Q.TApipath
	TBuildService = &Q.TBuildService
	TRelease = &Q.TRelease
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		TAccount:      newTAccount(db, opts...),
		TAllAuthxRule: newTAllAuthxRule(db, opts...),
		TApipath:      newTApipath(db, opts...),
		TBuildService: newTBuildService(db, opts...),
		TRelease:      newTRelease(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	TAccount      tAccount
	TAllAuthxRule tAllAuthxRule
	TApipath      tApipath
	TBuildService tBuildService
	TRelease      tRelease
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		TAccount:      q.TAccount.clone(db),
		TAllAuthxRule: q.TAllAuthxRule.clone(db),
		TApipath:      q.TApipath.clone(db),
		TBuildService: q.TBuildService.clone(db),
		TRelease:      q.TRelease.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		TAccount:      q.TAccount.replaceDB(db),
		TAllAuthxRule: q.TAllAuthxRule.replaceDB(db),
		TApipath:      q.TApipath.replaceDB(db),
		TBuildService: q.TBuildService.replaceDB(db),
		TRelease:      q.TRelease.replaceDB(db),
	}
}

type queryCtx struct {
	TAccount      ITAccountDo
	TAllAuthxRule ITAllAuthxRuleDo
	TApipath      ITApipathDo
	TBuildService ITBuildServiceDo
	TRelease      ITReleaseDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		TAccount:      q.TAccount.WithContext(ctx),
		TAllAuthxRule: q.TAllAuthxRule.WithContext(ctx),
		TApipath:      q.TApipath.WithContext(ctx),
		TBuildService: q.TBuildService.WithContext(ctx),
		TRelease:      q.TRelease.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
