apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: account
spec:
  hosts:
  - account
  http:
  # 默认出口
  - route:
    - destination:
        host: account
        subset: primary
