apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: <ns>
resources:
  - caddy-cm.yaml
  - deploymen.yaml
  - service.yaml

  - istio-dr.yaml
  - istio-vs.yaml

configMapGenerator:
  - name: caddy-<svc>-cm
    files:
      - Caddyfile
generatorOptions:
  disableNameSuffixHash: true

commonLabels: 
    service: <svc>
    service-type: web

# 精准更改指定deployment的pod配置
patches:
- target:
    kind: Deployment
    name: <svc>-<version>
  path: patch.yaml