// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTAccount = "t_accounts"

// TAccount mapped from table <t_accounts>
type TAccount struct {
	ID             int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name           string `gorm:"column:name;type:text" json:"name"`
	IsDeny         bool   `gorm:"column:is_deny;type:boolean;comment:拉黑禁止登陆标记" json:"is_deny"`    // 拉黑禁止登陆标记
	Roles          string `gorm:"column:roles;type:text[];comment:当前账户赋予的api权限角色集合" json:"roles"` // 当前账户赋予的api权限角色集合
	Phone          string `gorm:"column:phone;type:text" json:"phone"`
	FeishuOpenid   string `gorm:"column:feishu_openid;type:text" json:"feishu_openid"`
	FeishuUnionid  string `gorm:"column:feishu_unionid;type:text;comment:绑定账户飞书平台的唯一unionid" json:"feishu_unionid"` // 绑定账户飞书平台的唯一unionid
	FeishuNickname string `gorm:"column:feishu_nickname;type:text" json:"feishu_nickname"`
	FeishuAvatar   string `gorm:"column:feishu_avatar;type:text" json:"feishu_avatar"`
	WxOpenid       string `gorm:"column:wx_openid;type:text" json:"wx_openid"`
	WxUnionid      string `gorm:"column:wx_unionid;type:text;comment:绑定账户微信平台的唯一unionid" json:"wx_unionid"` // 绑定账户微信平台的唯一unionid
	CreateAt       int64  `gorm:"column:create_at;type:bigint" json:"create_at"`
	UpdateAt       int64  `gorm:"column:update_at;type:bigint" json:"update_at"`
	DeleteAt       int64  `gorm:"column:delete_at;type:bigint" json:"delete_at"`
}

// TableName TAccount's table name
func (*TAccount) TableName() string {
	return TableNameTAccount
}
