// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTRelease = "t_releases"

// TRelease mapped from table <t_releases>
type TRelease struct {
	ID                          int64  `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name                        string `gorm:"column:name;type:text;comment:可读的发布单名称，RFC3339命名" json:"name"`                                                                                // 可读的发布单名称，RFC3339命名
	Creator                     string `gorm:"column:creator;type:text;comment:发布单创建者" json:"creator"`                                                                                      // 发布单创建者
	FlowStatus                  int32  `gorm:"column:flow_status;type:integer;comment:最新流转状态" json:"flow_status"`                                                                           // 最新流转状态
	SchedWeight                 int32  `gorm:"column:sched_weight;type:integer;comment:调度权重值,高者优先" json:"sched_weight"`                                                                     // 调度权重值,高者优先
	IsRunning                   bool   `gorm:"column:is_running;type:boolean;comment:执行态状态" json:"is_running"`                                                                              // 执行态状态
	SelectedServiceVersionLists string `gorm:"column:selected_service_version_lists;type:jsonb;comment:发布目标服务的json列集合" json:"selected_service_version_lists"`                               // 发布目标服务的json列集合
	EnvType                     int32  `gorm:"column:env_type;type:integer;comment:发布目标环境，dev|prod" json:"env_type"`                                                                        // 发布目标环境，dev|prod
	OperateType                 string `gorm:"column:operate_type;type:text;comment:操作release的具体按钮动作需调度的类型绑定，init(默认)|primary(全量)|rollback(回滚)|quota(更新配置)|删除(delete)" json:"operate_type"` // 操作release的具体按钮动作需调度的类型绑定，init(默认)|primary(全量)|rollback(回滚)|quota(更新配置)|删除(delete)
	CideployFaildCount          int32  `gorm:"column:cideploy_faild_count;type:integer;comment:最大部署调度重试次数，超过阈值不在调度，web前端按钮主动显式操作方式:删除|重试" json:"cideploy_faild_count"`                      // 最大部署调度重试次数，超过阈值不在调度，web前端按钮主动显式操作方式:删除|重试
	CreateAt                    int64  `gorm:"column:create_at;type:bigint" json:"create_at"`
	UpdateAt                    int64  `gorm:"column:update_at;type:bigint" json:"update_at"`
	DeleteAt                    int64  `gorm:"column:delete_at;type:bigint" json:"delete_at"`
}

// TableName TRelease's table name
func (*TRelease) TableName() string {
	return TableNameTRelease
}
