apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploymen.yaml
  - istio-dr.yaml
  - istio-vs.yaml
commonLabels:
  service: account
  service-type: grpc

# 精准更改指定deployment的pod配置
patches:
  - target:
      kind: Deployment
      name: account-v24.0818
    path: patch.yaml