apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - auth.yaml
  - service-entry.yaml

configMapGenerator:
  - name: authx-cm
    files:
      - conf.yaml
      - dynamic.yaml
generatorOptions:
  disableNameSuffixHash: true